### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by HaishuoFang** [RingoTC/BERT-NER-ScienceIE#1]
hello，
Have you tested the metrics of bert-ner. The performance of the bert-based model on the development dataset is only around 76% accuracy?
Thank you

**Comment by RingoTC** [comment]
What dataset are you using? Perhaps because Transformer itself is insensitive to positional information, especially on some certain datasets, BERT can't achieve a better performance than previous models such as BiLSTM+CRF.

**Comment by HaishuoFang** [comment]
Thanks for you reply!
The dataset I am using is Semeval 2017 task 10: ScienceIE.

**Comment by RingoTC** [comment]
Yes, we tested on this dataset and the accuracy of this model is also very poor.

**Comment by HaishuoFang** [comment]
Thank you very much! I also think it is quite weird. Maybe I need to do error analysis
